### ISSUE TITLE
Incluir link para o ColorGoServer

### ISSUE THREAD

**Issue by HelcioAlex** [Brasil-Nihon-Kiin/nihonkiin.com.br#10]
Colocar link para o recém inaugurado ColorGoServer que está bem atraente para novatos.

**Comment by psygo** [comment]
@HelcioAlex, se você tiver mais sugestões e quiser discuti-las, também é possível conversar conosco no [chat do Gitter][gitter].


[gitter]: https://gitter.im/nihonkiin-com-br/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
