### ISSUE TITLE
Versão Inicial de Banco de Dados de Jogadores

### ISSUE THREAD

**Issue by psygo** [Brasil-Nihon-Kiin/nihonkiin.com.br#2]
Seria ideal que a Nihon Kiin mantivesse um cadastro de todos os jogadores brasileiros, isso ajudaria a centralizar os jogadores brasileiros como comunidade.

**Comment by laercioskt** [comment]
Seria interessante também que na sessão [Lista de Jogadores Brasileiros](https://nihonkiin.com.br/conteudo/principal/jogadores/jogadores.html) tivesse a lista dos jogadores(as) com seus contatos para caso alguém tivesse procurando por jogadores(as) na sua região.

Esse cadastro poderia ser mantido pelos moderadores, mas seria interessante um formulário para preenchimento e envio por email no próprio site.

Esse formulário poderia solicitar além dos dados da alteração [f4de2a7](https://github.com/Brasil-Nihon-Kiin/nihonkiin.com.br/commit/f4de2a7675436cc5a7347395c1e063a4e788a752), se o(a) jogador(a) gostaria de receber notificações de torneios por email.
Essa notificações poderiam ser separadas em vários grupos para não gerar muito spam.

**Comment by psygo** [comment]
> Seria interessante também que na sessão [Lista de Jogadores Brasileiros](https://nihonkiin.com.br/conteudo/principal/jogadores/jogadores.html) tivesse a lista dos jogadores(as) com seus contatos para caso alguém tivesse procurando por jogadores(as) na sua região.

Eu incluí dados como email, telefone e nome de perfil em determinado servidor pra ajudar nisso.

Vou adicionar um formulário de cadastramento que resulta em um `mailto`. É melhor do que nada, e nos poupa o trabalho de ter que criar um servidor ou banco de dados no Firebase.
