### ISSUE TITLE
Data de Nascimento deveria ser implementada com `<input type="date" />`

### ISSUE THREAD

**Issue by psygo** [Brasil-Nihon-Kiin/nihonkiin.com.br#20]
Veja o [último comentário][comment] do @laercioskt no #19.

[comment]: https://github.com/Brasil-Nihon-Kiin/nihonkiin.com.br/pull/19#discussion_r579870129

**Comment by laercioskt** [comment]
Integrada no commit https://github.com/Brasil-Nihon-Kiin/nihonkiin.com.br/commit/e7e5e69c2f7193e53441f565c65e070921679454

**Comment by psygo** [comment]
Quando vc for fazer o commit, escreva algo como `fixes #20` na própria mensagem do commit. O Github pega isso de forma automática e fecha o issue automaticamente. ([Exemplo][exemplo])


[exemplo]: https://stackoverflow.com/a/60027286/4756173
