### ISSUE TITLE
Primeiro parágrafo do site convidando o visitante à ajudar na construção do site poderia ficar apenas no README

### ISSUE THREAD

**Issue by laercioskt** [Brasil-Nihon-Kiin/nihonkiin.com.br#6]
Acredito que o primeiro paragrafo é voltado mais para desenvolvedores, então, poderia ser removido e um icone do GitHub adicionado ao lado dos icones das redes Facebook e Instagram.

Com isso acredito que desenvolvedores entenderão que poderão ajudar por ali, e para outros grupos acredito que poderia ser adicionado algum icone para essas contas de "suportadores", ou algum outro icone que represente ajuda.

**Comment by psygo** [comment]
Eu estava pensando nisso também, mas é que eu queria que ficasse um pouco mais explícito que *qualquer um* pode nos dar feedback sobre o site. Mas, até aí, há já um item chamado *Contato e Feedback* que direciona o usuário para cá de qualquer maneira.

A solução que eu estava pensando em fazer era pegar aquele parágrafo e colocá-lo em uma coluna ao lado da coluna de artigos, assim ele ainda existe mas não atrapalha o resto do design. O que você acha?

**Comment by laercioskt** [comment]
Acho que vale a pena manter por um tempo sim, só colocaria de baixo dos Artigos, inclusive, aproveitando, acho que a tabela de artigos poderia ir para de baixo do Calendário, ficando apenas o indice na "coluna" da esquerda do site.

**Comment by psygo** [comment]
Eu tava até pensando em meio que fazer um elemento (Web Component) de footer pra esse tipo de coisa, como esse texto do Github.

Em relação aos artigos ficando abaixo do calendário, pode ser, mas vai ficar mais difícil de fazer com que as coisas fiquem bonitinhas em dispositivos móveis, com menos largura. Sem falar que tem o problema de quantos itens de calendário e artigos deveríamos deixar na tela a princípio (paginação). Em dispositivos móveis, eu estava pensando em deixar tudo numa coluna só.

**Comment by laercioskt** [comment]
Entendi, ficará ruim mesmo.

Talvez só fazer o que você sugeriu então:

> A solução que eu estava pensando em fazer era pegar aquele parágrafo e colocá-lo em uma coluna ao lado da coluna de artigos, assim ele ainda existe mas não atrapalha o resto do design. O que você acha?

**Comment by psygo** [comment]
Acho que, a princípio, ficaria melhor mesmo. Se quiser, pode fazer.

Eu também tenho pensado sobre criar cartões (cards) para cada um dos 3 itens macros. Seriam 3 pequenos retângulos paralelos, como na [empresa em que você trabalha][objective]. Aí o calendário ficaria logo abaixo, em paralelo com a tabela de artigos, aí talvez caberia em uma versão mobile &mdash; em último caso, ficaria uma tabela em cima da outra.


[objective]: https://www.objective.com.br/

**Comment by psygo** [comment]
Se você puder, preferiria que você:

1. Criasse um cópia do template atual dentro do arquivo do Adobe XD.
2. Modificasse a cópia.

Assim, teríamos um histórico visual dos designs. Se você precisar de ajuda com o Adobe XD, me avise.
