### ISSUE TITLE
Livros

### ISSUE THREAD

**Issue by HelcioAlex** [Brasil-Nihon-Kiin/nihonkiin.com.br#9]
Colocar link para o livro do Felipe Herman

**Comment by psygo** [comment]
E qual seria o link?

**Comment by psygo** [comment]
@sagemerlin?

**Comment by sagemerlin** [comment]
https://educacao.sme.prefeitura.sp.gov.br/wp-content/uploads/2020/12/Miolo-e-Capa-GO-WEB-1.pdf

aqui
